name: "Ping URL"

on:
  push:
    branches:
      - main

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:  
    - name: deploy
      uses: alesil/actions-curl@v1.2
      with:
        curl: http://34.228.13.110:3002/git
